### ISSUE TITLE
Position fixed

### ISSUE THREAD

**Issue by icidasset** [jinjor/elm-contextmenu#1]
I needed to change the `position: fixed` style to `position: absolute` for it to work correctly.
Just so you know 😉  I think it has something to do with the scroll position?

PS. Thanks for this library!

**Comment by jinjor** [comment]
Thanks for your feedback.

You mean the menu should move synchronized with the scroll position? If I understand correctly, I think it is not a problem, but a preference.

I just tried it with three different browsers and one web app.

* Chrome: The menu immediately closes on start scroll
* Firefox: The menu keep "fixed" position during scroll
* Edge: Cannot start scroll when the menu is shown
* Google Spread Sheet: The menu moves with synchronized with the scroll position

Current behavior seems like the same as Firefox. You need one like Google Spread Sheet?

**Comment by icidasset** [comment]
No, I meant like, say you have a page that's scrollable, and the item that has `ContextMenu.open` attached to it has __no__ position fixed or absolute, then if you scroll down a bit and open the context menu there will be an offset.

I've uploaded a little video to show you:  
https://www.dropbox.com/s/ypd3bueljyhym2k/context.mov?dl=0

The 1st time I open the context menu I'm showing the correct behaviour,
and the 2nd time I'm showing the faulty scenario.

I hope that's more clear sorry 😄

**Comment by jinjor** [comment]
Oh, that seems a bug.

Thanks for pointing it out. I'll tell you when it is fixed :)

**Comment by jinjor** [comment]
Should be fixed. Thanks for your patience!

**Comment by icidasset** [comment]
Thank you! 😄
